backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "data"
    label: "Data"
    label_singular: "Data File"
    folder: "Data"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - label: "Type"
        name: "type"
        widget: "select"
        options:
          - { label: "Projects", value: "projects" }
          - { label: "Products", value: "products" }
      - label: "Items (for Projects)"
        name: "items"
        widget: "list"
        label_singular: "Item"
        condition:
          field: "type"
          equals: "projects"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Price"
            name: "price"
            widget: "number"
          - label: "Image"
            name: "image"
            widget: "image"
      - label: "Products"
        name: "products"
        widget: "list"
        label_singular: "Product"
        condition:
          field: "type"
          equals: "products"
        fields:
          - label: "Product Title"
            name: "title"
            widget: "string"
          - label: "Product Description"
            name: "description"
            widget: "text"
          - label: "Product Price"
            name: "price"
            widget: "number"
          - label: "Product Image"
            name: "image"
            widget: "image"