backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "data"
    label: "Data"
    files:
      - label: "Items"
        name: "items"
        file: "src/content/data/items.json"
        format: "json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            label_singular: "Item"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Description"
                name: "description"
                widget: "text"
              - label: "Price"
                name: "price"
                widget: "number"
              - label: "Image"
                name: "image"
                widget: "image"

      - label: "Products"
        name: "products"
        file: "src/content/data/products.json"
        format: "json"
        fields:
          - label: "Products"
            name: "products"
            widget: "list"
            label_singular: "Product"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Description"
                name: "description"
                widget: "text"
              - label: "Price"
                name: "price"
                widget: "number"
              - label: "Image"
                name: "image"
                widget: "image"