backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "items"
    label: "Items"
    label_singular: "Item File"
    folder: "src/content/data"
    create: true
    slug: "item-{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - label: "Items"
        name: "items"
        widget: "list"
        label_singular: "Item"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Price"
            name: "price"
            widget: "number"
          - label: "Image"
            name: "image"
            widget: "image"

  - name: "products"
    label: "Products"
    label_singular: "Product File"
    folder: "src/content/data"
    create: true
    slug: "product-{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - label: "Products"
        name: "products"
        widget: "list"
        label_singular: "Product"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Price"
            name: "price"
            widget: "number"
          - label: "Image"
            name: "image"
            widget: "image"