backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "projects"
    label: "Projects"
    files:
      - label: "Projects"
        name: "projects"
        file: "src/content/projects.json"
        format: "json"
        fields:
          - label: "Projects"
            name: "projects"
            widget: "list"
            label_singular: "Project"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Description"
                name: "description"
                widget: "text"
              - label: "Link"
                name: "link"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"